spring.datasource.url=jdbc:postgresql://localhost:5432/imdb_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

tmdb.api.key=351e1995339f916b9013dbcd9a405317

spring.application.name=imdb
server.port=8080
spring.main.banner-mode=off